---
title: "Final Project"
author: "Avi Kodali"
date: "2025-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(survey)
```

```{r}
adult2024 <- read.csv("adult24.csv", stringsAsFactors=FALSE)
```

```{r}
head(adult2024)
```

```{r}
adult2024$HICOSTR1_A
```


```{r}
invalid_values <- c(99999, 99998, 99997)
premium_data <- adult2024[(!is.na(adult2024$HICOSTR1_A) & !adult2024$HICOSTR1_A %in% invalid_values), ]
premium_data <- premium_data %>% filter(PRPLCOV1_A == 2 & POLHLD1_A == 1)
premium_data <- premium_data %>% select(HICOSTR1_A, #response y
                                        AGEP_A, SEX_A, RACEALLP_A, HISPALLP_A, MARITAL_A, NATUSBORN_A, ORIENT_A, #demographic
                                        POVRATTC_A, RATCAT_A, EDUCP_A, EMPLASTWK_A, EMPNOWRK_A, EMPWHYNOT_A, EMPWHENWRK_A, EMDOCCUPN2_A, EMDOCCUPN1_A, ACCSSINT_A, EMDINDSTN1_A, #socioeconomic
                                        DIBEV_A, PREDIB_A, GESDIB_A, HYPEV_A, ASEV_A, LONGCOVD2_A, EVERCOVD_A, ANXFREQ_A,DEPFREQ_A, #health conditions
                                        SMOKELSEV1_A, SMKCIGST_A, DRKLIFE_A, DRK12MWK_A, DRKSTAT_A, MODFREQW_A, #health related behaviors
                                        REGION, URBRRL23, #geography
                                        MEDICARE_A, MCPART_A, MCCHOICE_A, PRIVATE_A, EXCHANGE_A, PLNWRKR1_A, #access to care
                                        PPSU, PSTRAT, WTFA_A)#survey design

head(premium_data)
```

```{r}
premium_data$AGEP_A[premium_data$AGEP_A %in% c(97, 98, 99)] <- NA
premium_data$SEX_A[premium_data$SEX_A %in% c(7,8,9)] <- NA
premium_data$RACEALLP_A[premium_data$RACEALLP_A %in% c(7,8,9)] <- NA
premium_data$HISPALLP_A[premium_data$HISPALLP_A %in% c(97,98,99)] <- NA
premium_data$MARITAL_A[premium_data$MARITAL_A %in% c(7,8,9)] <- NA
premium_data$NATUSBORN_A[premium_data$NATUSBORN_A %in% c(7,8,9)] <- NA
premium_data$ORIENT_A[premium_data$ORIENT_A %in% c(7,8)] <- NA
premium_data$RATCAT_A[premium_data$RATCAT_A %in% c(98)] <- NA
premium_data$EDUCP_A[premium_data$EDUCP_A %in% c(97,98,99)] <- NA
premium_data$EMPLASTWK_A[premium_data$EMPLASTWK_A %in% c(7,8,9)] <- NA
premium_data$EMPNOWRK_A[premium_data$EMPNOWRK_A %in% c(7,8,9)] <- NA
premium_data$EMPWHYNOT_A[premium_data$EMPWHYNOT_A %in% c(97,98,99)] <- NA
premium_data$EMPWHENWRK_A[premium_data$EMPWHENWRK_A %in% c(7,8,9)] <- NA
premium_data$EMDOCCUPN2_A[premium_data$EMDOCCUPN2_A %in% c(97,98,99)] <- NA
premium_data$EMDOCCUPN1_A[premium_data$EMDOCCUPN1_A %in% c(97,98,99)] <- NA
premium_data$ACCSSINT_A[premium_data$ACCSSINT_A %in% c(7,8,9)] <- NA
premium_data$EMDINDSTN1_A[premium_data$EMDINDSTN1_A %in% c(97,98,99)] <- NA
premium_data$NATUSBORN_A[premium_data$NATUSBORN_A %in% c(7,8,9)] <- NA
premium_data$DIBEV_A[premium_data$DIBEV_A %in% c(7,8,9)] <- NA
premium_data$PREDIB_A [premium_data$PREDIB_A %in% c(7,8,9)] <- NA
premium_data$GESDIB_A[premium_data$GESDIB_A %in% c(7,8,9)] <- NA
premium_data$HYPEV_A[premium_data$HYPEV_A %in% c(7,8,9)] <- NA
premium_data$ASEV_A[premium_data$ASEV_A %in% c(7,8,9)] <- NA
premium_data$LONGCOVD2_A [premium_data$LONGCOVD2_A %in% c(7,8,9)] <- NA
premium_data$EVERCOVD_A[premium_data$EVERCOVD_A %in% c(7,8,9)] <- NA
premium_data$ANXFREQ_A[premium_data$ANXFREQ_A %in% c(7,8,9)] <- NA
premium_data$DEPFREQ_A[premium_data$DEPFREQ_A %in% c(7,8,9)] <- NA
premium_data$SMOKELSEV1_A[premium_data$SMOKELSEV1_A %in% c(7,8,9)] <- NA
premium_data$SMKCIGST_A[premium_data$SMKCIGST_A %in% c(9)] <- NA
premium_data$DRKLIFE_A[premium_data$DRKLIFE_A %in% c(7,8,9)] <- NA
premium_data$DRK12MWK_A[premium_data$DRK12MWK_A %in% c(97,98,99)] <- NA
premium_data$DRKSTAT_A[premium_data$DRKSTAT_A %in% c(10)] <- NA
premium_data$MODFREQW_A[premium_data$MODFREQW_A %in% c(97,98,99)] <- NA
premium_data$MEDICARE_A[premium_data$MEDICARE_A %in% c(7,8,9)] <- NA
premium_data$MCPART_A[premium_data$MCPART_A %in% c(7,8,9)] <- NA
premium_data$MCCHOICE_A[premium_data$MCCHOICE_A %in% c(7)] <- NA
premium_data$PRIVATE_A[premium_data$PRIVATE_A %in% c(7,8,9)] <- NA
premium_data$EXCHANGE_A[premium_data$EXCHANGE_A %in% c(8)] <- NA
premium_data$PLNWRKR1_A[premium_data$PLNWRKR1_A %in% c(97,98,99)] <- NA
summary(premium_data)
head(premium_data)
```

```{r}
premium_data <- premium_data %>% mutate(across(c(SEX_A, RACEALLP_A, HISPALLP_A, MARITAL_A, NATUSBORN_A, ORIENT_A,
                                                 RATCAT_A, EDUCP_A, EMPLASTWK_A, EMPNOWRK_A, EMPWHYNOT_A, EMPWHENWRK_A, EMDOCCUPN2_A, EMDOCCUPN1_A, ACCSSINT_A, EMDINDSTN1_A,
                                                 DIBEV_A, PREDIB_A, GESDIB_A, HYPEV_A, ASEV_A, LONGCOVD2_A, EVERCOVD_A, ANXFREQ_A,DEPFREQ_A,
                                                 SMOKELSEV1_A, SMKCIGST_A, DRKLIFE_A, DRK12MWK_A, DRKSTAT_A, MODFREQW_A,
                                                 REGION, URBRRL23,
                                                 MEDICARE_A, MCPART_A, MCCHOICE_A, EXCHANGE_A, PLNWRKR1_A),as.factor))
summary(premium_data)
```

```{r}
premium_data <- premium_data %>% 
  mutate(SEX_A = case_when(SEX_A == 1 ~ "M", 
                           SEX_A == 2 ~ "F",
                           .default = NA),
         RACEALLP_A = case_when(RACEALLP_A == 1 ~ "White",
                                RACEALLP_A == 2 ~ "African-American",
                                RACEALLP_A == 3 ~ "Asian",
                                RACEALLP_A == 4 ~ "AIAN",
                                RACEALLP_A == 5 ~ "AIAN+Grp",
                                RACEALLP_A == 6 ~ "Other S/M",
                                .default = NA),
         HISPALLP_A = case_when(HISPALLP_A == 1 ~ "Hispanic",
                                HISPALLP_A == 2 ~ "NH-White",
                                HISPALLP_A == 3 ~ "NH-African-American",
                                HISPALLP_A == 4 ~ "NH-Asian",
                                HISPALLP_A == 5 ~ "NH_AIAN",
                                HISPALLP_A == 6 ~ "NH-AIAN+Grp",
                                HISPALLP_A == 7 ~ "Other S/M",
                                .default = NA),
         MARITAL_A = case_when(MARITAL_A == 1 ~ "Married",
                               MARITAL_A == 2 ~ "Living Together",
                               MARITAL_A == 3 ~ "Neither",
                               .default = NA),
         NATUSBORN_A = case_when(NATUSBORN_A == 1 ~ "Yes",
                                 NATUSBORN_A == 2 ~ "No",
                                 .default = NA),
         ORIENT_A = case_when(ORIENT_A == 1 ~ "GayLesbian",
                              ORIENT_A == 2 ~ "Straight",
                              ORIENT_A == 3 ~ "Bisexual",
                              ORIENT_A == 4 ~ "Something else",
                              ORIENT_A == 5 ~ "Don't Know",
                              .default = NA),
         EDUCP_A = case_when(EDUCP_A == 0 ~ "Never/KG",
                             EDUCP_A == 1 ~ "Gr1-11",
                             EDUCP_A == 2 ~ "Gr12,No Diploma",
                             EDUCP_A == 3 ~ "GED",
                             EDUCP_A == 4 ~ "HS Grad",
                             EDUCP_A == 5 ~ "Some College",
                             EDUCP_A == 6 ~ "Assoc Dg: OCC, TECH, VOC",
                             EDUCP_A == 7 ~ "Assoc Dg: Acad",
                             EDUCP_A == 8 ~ "Bachelors",
                             EDUCP_A == 9 ~ "Masters",
                             EDUCP_A == 10 ~ "Profess/Doc",
                             .default = NA),
         ACCSSINT_A = case_when(ACCSSINT_A == 1 ~ "Yes",
                                ACCSSINT_A == 2 ~ "No",
                                .default = NA),
         DIBEV_A = case_when(DIBEV_A == 1 ~ "Yes",
                             DIBEV_A == 2 ~ "No",
                             .default = NA),
         PREDIB_A = case_when(PREDIB_A == 1 ~ "Yes",
                              PREDIB_A == 2 ~ "No",
                              .default = NA),
         HYPEV_A = case_when(HYPEV_A == 1 ~ "Yes",
                             HYPEV_A == 2 ~ "No",
                             .default = NA),
         ASEV_A = case_when(ASEV_A == 1 ~ "Yes",
                            ASEV_A == 2 ~ "No",
                            .default = NA),
         EVERCOVD_A = case_when(EVERCOVD_A == 1 ~ "Yes",
                                EVERCOVD_A == 2 ~ "No",
                                .default = NA),
         ANXFREQ_A = case_when(ANXFREQ_A == 1 ~ "Daily",
                               ANXFREQ_A == 2 ~ "Weekly",
                               ANXFREQ_A == 3 ~ "Monthly",
                               ANXFREQ_A == 4 ~ "Few times/year",
                               ANXFREQ_A == 5 ~ "Never",
                               .default = NA),
         DEPFREQ_A = case_when(DEPFREQ_A == 1 ~ "Daily",
                               DEPFREQ_A == 2 ~ "Weekly",
                               DEPFREQ_A == 3 ~ "Monthly",
                               DEPFREQ_A == 4 ~ "Few times/year",
                               DEPFREQ_A == 5 ~ "Never",
                               .default = NA),
         SMOKELSEV1_A = case_when(SMOKELSEV1_A == 1 ~ "Yes",
                                  SMOKELSEV1_A == 2 ~ "No",
                                  .default = NA),
         SMKCIGST_A = case_when(SMKCIGST_A == 1 ~ "Current everyday",
                                SMKCIGST_A == 2 ~ "Current some day",
                                SMKCIGST_A == 3 ~ "Former",
                                SMKCIGST_A == 4 ~ "Never",
                                SMKCIGST_A == 5 ~ "Smoker, status unknown",
                                .default = NA),
         DRKLIFE_A = case_when(DRKLIFE_A == 1 ~ "Yes",
                               DRKLIFE_A == 2 ~ "No",
                               .default = NA),
         DRK12MWK_A = case_when(DRK12MWK_A == 0 ~ "< 1 day/week",
                                DRK12MWK_A == 1 ~ "1 day/week",
                                DRK12MWK_A == 2 ~ "2 day/week",
                                DRK12MWK_A == 3 ~ "3 day/week",
                                DRK12MWK_A == 4 ~ "4 day/week",
                                DRK12MWK_A == 5 ~ "5 day/week",
                                DRK12MWK_A == 6 ~ "6 day/week",
                                DRK12MWK_A == 7 ~ "7 day/week",
                                DRK12MWK_A == 95 ~ "Did not drink in past year",
                                .default = NA),
         DRKSTAT_A = case_when(DRKSTAT_A == 1 ~ "Lifetime abstainer",
                               DRKSTAT_A == 2 ~ "Former infrequent",
                               DRKSTAT_A == 3 ~ "Former inregular",
                               DRKSTAT_A == 4 ~ "Former, freq unknown",
                               DRKSTAT_A == 5 ~ "Current infrequent",
                               DRKSTAT_A == 6 ~ "Current light",
                               DRKSTAT_A == 7 ~ "Current moderate",
                               DRKSTAT_A == 8 ~ "Current heavier",
                               DRKSTAT_A == 9 ~ "Current, freq unknown",
                               .default = NA),
         MODFREQW_A = case_when(MODFREQW_A == 0 ~ "< 1 time/week",
                                MODFREQW_A == 1 ~ "1 time/week",
                                MODFREQW_A == 2 ~ "2 time/week",
                                MODFREQW_A == 3 ~ "3 time/week",
                                MODFREQW_A == 4 ~ "4 time/week",
                                MODFREQW_A == 5 ~ "5 time/week",
                                MODFREQW_A == 6 ~ "6 time/week",
                                MODFREQW_A == 7 ~ "7 time/week",
                                MODFREQW_A == 8 ~ "8 time/week",
                                MODFREQW_A == 9 ~ "9 time/week",
                                MODFREQW_A == 10 ~ "10 time/week",
                                MODFREQW_A == 11 ~ "11 time/week",
                                MODFREQW_A == 12 ~ "12 time/week",
                                MODFREQW_A == 13 ~ "13 time/week",
                                MODFREQW_A == 14 ~ "14 time/week",
                                MODFREQW_A == 15 ~ "15 time/week",
                                MODFREQW_A == 16 ~ "16 time/week",
                                MODFREQW_A == 17 ~ "17 time/week",
                                MODFREQW_A == 18 ~ "18 time/week",
                                MODFREQW_A == 19 ~ "19 time/week",
                                MODFREQW_A == 20 ~ "20 time/week",
                                MODFREQW_A == 21 ~ "21 time/week",
                                MODFREQW_A == 22 ~ "22 time/week",
                                MODFREQW_A == 23 ~ "23 time/week",
                                MODFREQW_A == 24 ~ "24 time/week",
                                MODFREQW_A == 25 ~ "25 time/week",
                                MODFREQW_A == 26 ~ "26 time/week",
                                MODFREQW_A == 27 ~ "27 time/week",
                                MODFREQW_A == 28 ~ "28 time/week",
                                MODFREQW_A == 94 ~ "Never",
                                MODFREQW_A == 96 ~ "Unable",
                                .default = NA),
         REGION = case_when(REGION == 1 ~ "Northeast",
                            REGION == 2 ~ "Midwest",
                            REGION == 3 ~ "South",
                            REGION == 4 ~ "West",
                            .default = NA),
         URBRRL23 = case_when(URBRRL23 == 1 ~ "Large central metro",
                              URBRRL23 == 2 ~ "Large fringe metro",
                              URBRRL23 == 3 ~ "Medium and small metro",
                              URBRRL23 == 4 ~ "Nonmetropolitan",
                              .default = NA))

head(premium_data)
```

```{r}
sort(colSums(is.na(premium_data)), decreasing = TRUE)
```

```{r}
premium_data <- premium_data %>% select(HICOSTR1_A, #response y
                                        AGEP_A, SEX_A, RACEALLP_A, HISPALLP_A, MARITAL_A, NATUSBORN_A, ORIENT_A, #demographic
                                        POVRATTC_A, RATCAT_A, EDUCP_A, EMDOCCUPN2_A, EMDOCCUPN1_A, ACCSSINT_A, EMDINDSTN1_A, #socio-economic
                                        DIBEV_A, PREDIB_A, GESDIB_A, HYPEV_A, ASEV_A, LONGCOVD2_A, EVERCOVD_A, ANXFREQ_A,DEPFREQ_A, #health conditions
                                        SMOKELSEV1_A, SMKCIGST_A, DRKLIFE_A, DRK12MWK_A, DRKSTAT_A, MODFREQW_A, #health related behaviors
                                        REGION, URBRRL23, #geography
                                        MCPART_A, MCCHOICE_A, EXCHANGE_A, PLNWRKR1_A, #access to care
                                        PPSU, PSTRAT, WTFA_A)#survey design
sort(colSums(is.na(premium_data)), decreasing = TRUE)
```

```{r}
premium_data %>% 
  ggplot(aes(x = HICOSTR1_A)) +
  geom_histogram(bins = 50, fill = "skyblue", color = "black") +
  labs(title = "Distribution of Premiums")

premium_data %>% 
  ggplot(aes(x = log(HICOSTR1_A))) +
  geom_histogram(bins = 50, fill = "skyblue", color = "black")
```

```{r}
premium_data %>%
  filter(!is.na(SMKCIGST_A)) %>%
  ggplot(aes(x = SMKCIGST_A, y = HICOSTR1_A, fill = SMKCIGST_A)) +
  geom_violin(trim = FALSE, alpha = 0.5) +
  geom_boxplot(width = 0.2, fill = "white", outlier.shape = NA) +
  scale_y_continuous(limits = c(0, 20000)) + 
  theme(legend.position = "none") +
  labs(title = "Impact of Smoking Status on Premiums",
       x = "Smoking Status",
       y = "Premium Cost ($)")
```

```{r}
premium_data %>%
  filter(!is.na(PLNWRKR1_A)) %>%
  mutate(PLNWRKR1_A = fct_reorder(PLNWRKR1_A, HICOSTR1_A, .fun = median)) %>%
  ggplot(aes(x = PLNWRKR1_A, y = HICOSTR1_A, fill = PLNWRKR1_A)) +
  geom_boxplot(outlier.alpha = 0.3) +
  coord_flip() +
  theme(legend.position = "none") +
  labs(title = "Healthcare Premiums by Plan Source",
       x = NULL,
       y = "Premium Cost ($)")
```

```{r}
edu_levels <- c("Never/KG", "Gr1-11", "Gr12,No Diploma", "GED", "HS Grad", 
                "Some College", "Assoc Dg: OCC, TECH, VOC", "Assoc Dg: Acad", 
                "Bachelors", "Masters", "Profess/Doc")

premium_data %>%
  filter(!is.na(EDUCP_A)) %>%
  mutate(EDUCP_A = factor(EDUCP_A, levels = edu_levels)) %>%
  ggplot(aes(x = EDUCP_A, y = HICOSTR1_A)) +
  geom_boxplot(fill = "blue", alpha = 0.6) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Socioeconomic Gradient: Education vs. Premium",
       x = "Education Level",
       y = "Premium Cost ($)")
```

```{r}
premium_data %>% 
  ggplot(aes(x = AGEP_A, y = HICOSTR1_A)) +
  geom_point() +
  geom_smooth(method = "gam", color = "red", se = TRUE) + 
  labs(title = "Relationship Between Age and Premium Cost",
       subtitle = "Red line indicates the smoothed trend",
       x = "Age (Years)",
       y = "Premium Cost ($)")
```

```{r}
premium_data %>%
  filter(!is.na(REGION) & !is.na(URBRRL23)) %>%
  group_by(REGION, URBRRL23) %>%
  summarise(
    Avg_Cost = mean(HICOSTR1_A, na.rm = TRUE),
    SE = sd(HICOSTR1_A, na.rm = TRUE) / sqrt(n())
  ) %>%
  ggplot(aes(x = REGION, y = Avg_Cost, fill = URBRRL23)) +
  geom_bar(stat = "identity", position = position_dodge(0.9), alpha = 0.8) +
  geom_errorbar(aes(ymin = Avg_Cost - 1.96*SE, ymax = Avg_Cost + 1.96*SE),
                position = position_dodge(0.9), width = 0.25) +
  labs(title = "Average Premium by Region and Urbanicity",
       y = "Mean Premium Cost ($)",
       fill = "Urban Status")
```

```{r}
premium_data %>%
  mutate(
    Comorbidity_Score = (HYPEV_A == "Yes") + (ASEV_A == "Yes") + 
                        (DIBEV_A == "Yes") + (EVERCOVD_A == "Yes")
  ) %>%
  filter(!is.na(Comorbidity_Score)) %>%
  ggplot(aes(x = factor(Comorbidity_Score), y = HICOSTR1_A)) +
  geom_boxplot(fill = "salmon", alpha = 0.6) +
  labs(title = "Impact of Comorbidity Burden on Premiums",
       subtitle = "Sum of Hypertension, Asthma, Diabetes, and Ever-COVID",
       x = "Number of Chronic Conditions",
       y = "Premium Cost ($)")
```

```{r}
anx_levels <- c("Daily", "Weekly", "Monthly", "Few times/year", "Never")

premium_data %>%
  filter(!is.na(ANXFREQ_A)) %>%
  mutate(ANXFREQ_A = factor(ANXFREQ_A, levels = anx_levels)) %>%
  ggplot(aes(x = ANXFREQ_A, y = HICOSTR1_A, fill = ANXFREQ_A)) +
  geom_boxplot(outlier.shape = NA) +
  scale_y_continuous(limits = c(0, 20000)) +
  scale_fill_brewer(palette = "PuBuGn", direction = -1) +
  theme(legend.position = "none") +
  labs(title = "Anxiety Frequency vs. Healthcare Premiums",
       x = "How Often Do You Feel Anxious?",
       y = "Premium Cost ($)")
```

```{r}
premium_data %>%
  filter(!is.na(SEX_A)) %>%
  ggplot(aes(x = HICOSTR1_A, fill = SEX_A)) +
  geom_density(alpha = 0.5) +
  scale_x_continuous(limits = c(0, 25000)) +
  theme_minimal() +
  labs(title = "Density of Premium Costs by Sex",
       x = "Premium Cost ($)",
       y = "Density",
       fill = "Sex")
```

```{r}
premium_data %>%
  filter(!is.na(RACEALLP_A)) %>%
  mutate(RACEALLP_A = fct_reorder(RACEALLP_A, HICOSTR1_A, .fun = median)) %>%
  ggplot(aes(x = RACEALLP_A, y = HICOSTR1_A, fill = RACEALLP_A)) +
  geom_boxplot(alpha = 0.7, outlier.alpha = 0.3) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Premium Costs by Racial Group",
       subtitle = "Ordered by median premium cost",
       x = "Race/Ethnicity",
       y = "Premium Cost ($)")
```

```{r}
premium_data %>%
  filter(!is.na(MARITAL_A)) %>%
  ggplot(aes(x = MARITAL_A, y = HICOSTR1_A, fill = MARITAL_A)) +
  geom_violin(trim = FALSE, alpha = 0.4) +
  geom_boxplot(width = 0.2, fill = "white", outlier.shape = NA) +
  theme(legend.position = "none") +
  labs(title = "Marital Status and Premium Costs",
       subtitle = "Married individuals may be carrying family plans (higher cost)",
       x = "Marital Status",
       y = "Premium Cost ($)")
```

```{r}
premium_data %>%
  filter(!is.na(LONGCOVD2_A)) %>%
  ggplot(aes(x = LONGCOVD2_A, y = HICOSTR1_A, fill = LONGCOVD2_A)) +
  geom_boxplot(width = 0.5) +
  scale_fill_manual(values = c("Yes" = "#E69F00", "No" = "#56B4E9")) +
  theme(legend.position = "none") +
  labs(title = "Do Individuals with Long COVID Pay More?",
       x = "Has Long COVID?",
       y = "Premium Cost ($)")
```

```{r}
premium_data %>%
  filter(!is.na(DRKSTAT_A)) %>%
  mutate(DRKSTAT_A = fct_reorder(DRKSTAT_A, HICOSTR1_A, .fun = median)) %>%
  ggplot(aes(x = DRKSTAT_A, y = HICOSTR1_A, fill = DRKSTAT_A)) +
  geom_boxplot(outlier.alpha = 0.2) +
  coord_flip() + 
  theme(legend.position = "none") +
  labs(title = "Alcohol Consumption Status vs. Premiums",
       x = NULL,
       y = "Premium Cost ($)")
```

```{r}
svy_design <- svydesign(
  id = ~PPSU,           
  strata = ~PSTRAT,    
  weights = ~WTFA_A,    
  data = premium_data,
  nest = TRUE
)
```

```{r}
premium_model <- svyglm(HICOSTR1_A ~ AGEP_A + SEX_A + RACEALLP_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + 
                                        POVRATTC_A + RATCAT_A + EDUCP_A + ACCSSINT_A +  
                                        DIBEV_A +  PREDIB_A + HYPEV_A +  ASEV_A +  EVERCOVD_A + ANXFREQ_A + DEPFREQ_A +
                                        SMOKELSEV1_A + SMKCIGST_A + DRKLIFE_A + DRKSTAT_A + MODFREQW_A +
                                        REGION + URBRRL23,
                          design = svy_design)
summary(premium_model)
```

```{r}
ggplot(svy_design$variables, aes(x = AGEP_A, y = HICOSTR1_A)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "loess")

#Continuous POVRATTC_A Linearity Check
ggplot(svy_design$variables, aes(x = POVRATTC_A, y = HICOSTR1_A)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "loess")

#Variance of residuals, should be constant - plot residuals against predicted, should be randomly scattered no pattern
#Residuals vs Fitted

resid_df <- data.frame(
  Fitted = fitted(premium_model),
  Residuals = residuals(premium_model, type = "deviance")
)

ggplot(resid_df, aes(x = Fitted, y = Residuals)) +
  geom_point(alpha = 0.6) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  geom_smooth(method = "loess", color = "blue", se = FALSE) +
  labs(
    title = "Residuals vs Fitted Values",
    x = "Fitted Values",
    y = "Residuals"
  )

#Histogram of Residuals
ggplot(resid_df, aes(x = Residuals)) +
  geom_histogram(bins = 30, fill = "blue", alpha = 0.6) +
  labs(title = "Histogram of Residuals")

```

```{r}
alias(premium_model)$Complete #DRKSTAT is collinear?
```

```{r}
library(car)
vif(lm(HICOSTR1_A ~ AGEP_A + POVRATTC_A,
       data = svy_design$variables))
```

```{r}
# Correlation matrix for continuous predictors
cont_vars <- c("AGEP_A", "POVRATTC_A", "HICOSTR1_A")
cor(svy_design$variables[, cont_vars], use = "complete.obs")
```

```{r}
# Fit lm for diagnostics
all_vars <- names(premium_data)[!names(premium_data) %in% c("HICOSTR1_A", "PPSU", "PSTRAT", "WTFA_A")]
lm_model <- lm(HICOSTR1_A ~ ., data = svy_design$variables %>% select(HICOSTR1_A, all_of(all_vars)))

# Cook's distance
cooks <- cooks.distance(lm_model)
plot(cooks, type="h", main="Cook's Distance")
abline(h = 4/(nrow(svy_design$variables)), col="red", lty=2)
```

```{r}
# Hat values
hat_vals <- hatvalues(lm_model)
plot(hat_vals, type="h")
abline(h = 2*mean(hat_vals), col="red", lty=2)
```

```{r}
#mean of residuals should be 0

mean(residuals(premium_model))
```

```{r}
#Normality of errors, residuals should be normally distributed -histogram for residuals (bell curve if normal)
#Q-Q - Plot

ggplot(resid_df, aes(sample = Residuals)) +
  stat_qq(color = "blue") +
  stat_qq_line(color = "red", linetype = "dashed") +
  theme_minimal() +
  labs(title = "QQ Plot of Deviance Residuals",
       x = "Theoretical Quantiles",
       y = "Sample Quantiles")
```

```{r}

#Leverage Points

#Jackknife Residuals & Bonferonni Correction

#Influential Points w/ Cooks Distance - Half Normal Plot

#Condition Number


############# Covariate Selection & Analysis ######################
#Hypothesis Test

#Confidence Interval

#F-Test/Anova
#remove each category from model
#Do one of health conditions affect health insurance premium?

premium_model_nohealth <- svyglm(HICOSTR1_A ~ AGEP_A + RACEALLP_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + #demographic
                                                    POVRATTC_A + RATCAT_A + EDUCP_A + ACCSSINT_A + #socio-economic
                                                    #DIBEV_A + PREDIB_A + HYPEV_A + ASEV_A + ANXFREQ_A + DEPFREQ_A + #health conditions
                                                    SMOKELSEV1_A + SMKCIGST_A + DRKSTAT_A + MODFREQW_A + #health related behaviors
                                                    REGION + URBRRL23 + #geography
                                                    SEX_A + EVERCOVD_A,
                                                    #SEX_A * GESDIB_A + LONGCOVD2_A * EVERCOVD_A + DRKLIFE_A * DRK12MWK_A, #interactions: EMDOCCUPN2_A,EMDOCCUPN1_A,EMDINDSTN1_A,MCPART_A,MCCHOICE_A,EXCHANGE_A,PLNWRKR1_A
                                                    design = svy_design)

anova(premium_model_nohealth, premium_model)
```

```{r}
#Residual Standard Error/R^2 vs Num of Predictors
covariates <- c(
  "AGEP_A", "RACEALLP_A", "HISPALLP_A", "MARITAL_A", "NATUSBORN_A",
  "ORIENT_A", "POVRATTC_A", "RATCAT_A", "EDUCP_A", "ACCSSINT_A",
  "DIBEV_A", "PREDIB_A", "HYPEV_A", "ASEV_A", "ANXFREQ_A", "DEPFREQ_A",
  "SMOKELSEV1_A", "SMKCIGST_A", "DRKSTAT_A", "MODFREQW_A",
  "REGION", "URBRRL23", "SEX_A", "EVERCOVD_A", "DRKLIFE_A"
)


rse_values <- numeric(length(covariates))

for(i in 1:length(covariates)) {
  # Create formula with first i covariates
  formula_i <- as.formula(
    paste("HICOSTR1_A ~", paste(covariates[1:i], collapse = "+"))
  )
  
  # Fit survey-weighted model
  model_i <- svyglm(formula_i, design = svy_design)
  
  # Extract residual standard error from dispersion
  rse_values[i] <- sqrt(summary(model_i)$dispersion)
}

# Combine into a data frame for plotting
rse_df <- data.frame(
  NumCovariates = 1:length(covariates),
  RSE = rse_values
)

ggplot(rse_df, aes(x = NumCovariates, y = RSE)) +
  geom_line(color = "blue") +
  geom_point(color = "red") +
  theme_minimal() +
  labs(
    title = "Residual Standard Error vs. Number of Covariates (Survey-Weighted)",
    x = "Number of Covariates",
    y = "Residual Standard Error"
  ) +
  scale_x_continuous(breaks = 1:length(covariates))
```

```{r}
#Partial Regression Plot for POVRATTC_A
# 1. Residuals of Y after all other predictors
resid_y <- residuals(svyglm(HICOSTR1_A ~ AGEP_A + RACEALLP_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + #demographic
                                               RATCAT_A + EDUCP_A + ACCSSINT_A + #socio-economic
                                               DIBEV_A + PREDIB_A + HYPEV_A + ASEV_A + ANXFREQ_A + DEPFREQ_A + #health conditions
                                               SMOKELSEV1_A + SMKCIGST_A + DRKSTAT_A + MODFREQW_A + #health related behaviors
                                               REGION + URBRRL23 + #geography
                                               SEX_A + EVERCOVD_A + DRKLIFE_A,
                                             #SEX_A * GESDIB_A + LONGCOVD2_A * EVERCOVD_A + DRKLIFE_A * DRK12MWK_A, #interactions: EMDOCCUPN2_A,EMDOCCUPN1_A,EMDINDSTN1_A,MCPART_A,MCCHOICE_A,EXCHANGE_A,PLNWRKR1_A
                                             design = svy_design))

# 2. Residuals of X_j after all other predictors
resid_x <- residuals(svyglm(POVRATTC_A ~ AGEP_A + RACEALLP_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + #demographic
                              RATCAT_A + EDUCP_A + ACCSSINT_A + #socio-economic
                              DIBEV_A + PREDIB_A + HYPEV_A + ASEV_A + ANXFREQ_A + DEPFREQ_A + #health conditions
                              SMOKELSEV1_A + SMKCIGST_A + DRKSTAT_A + MODFREQW_A + #health related behaviors
                              REGION + URBRRL23 + #geography
                              SEX_A + EVERCOVD_A + DRKLIFE_A,
                            #SEX_A * GESDIB_A + LONGCOVD2_A * EVERCOVD_A + DRKLIFE_A * DRK12MWK_A, #interactions: EMDOCCUPN2_A,EMDOCCUPN1_A,EMDINDSTN1_A,MCPART_A,MCCHOICE_A,EXCHANGE_A,PLNWRKR1_A
                            design = svy_design))

partial_df <- data.frame(
  Residual_Y = resid_y,
  Residual_X = resid_x
)

ggplot(partial_df, aes(x = Residual_X, y = Residual_Y)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", color = "blue", se = FALSE) +
  theme_minimal() +
  labs(title = "Partial Regression Plot for POVRATTC_A",
       x = "Residuals of POVRATTC_A ~ other predictors",
       y = "Residuals of HICOSTR1_A ~ other predictors")

```

```{r}
premium_log_model <- svyglm(log(HICOSTR1_A) ~ AGEP_A + SEX_A + RACEALLP_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + 
                                        POVRATTC_A + RATCAT_A + EDUCP_A + ACCSSINT_A +  
                                        DIBEV_A +  PREDIB_A + HYPEV_A +  ASEV_A +  EVERCOVD_A + ANXFREQ_A + DEPFREQ_A +
                                        SMOKELSEV1_A + SMKCIGST_A + DRKLIFE_A + DRKSTAT_A + MODFREQW_A +
                                        REGION + URBRRL23,
                          design = svy_design)

residuals_comparison <- bind_rows(
  data.frame(
    Residuals = residuals(premium_model, type = "deviance"),
    Model_Type = "Base Linear Model"
  ),
  data.frame(
    Residuals = residuals(premium_log_model, type = "deviance"),
    Model_Type = "Log-Transformed Model"
  )
)

ggplot(residuals_comparison, aes(sample = Residuals)) +
  stat_qq(aes(color = Model_Type), alpha = 0.6) +
  stat_qq_line(color = "black", linetype = "dashed") +
  facet_wrap(~Model_Type, scales = "free") +
  theme_minimal() +
  scale_color_manual(values = c("Base Linear Model" = "red", "Log-Transformed Model" = "blue")) +
  labs(
    title = "Diagnostic Check: Normality of Residuals",
    x = "Theoretical Quantiles",
    y = "Sample Quantiles"
  ) +
  theme(legend.position = "none")
```

```{r}
sum(premium_data$HICOSTR1_A == 0, na.rm = TRUE)

min(premium_data$HICOSTR1_A[premium_data$HICOSTR1_A > 0], na.rm = TRUE)
max(premium_data$HICOSTR1_A[premium_data$HICOSTR1_A > 0], na.rm = TRUE)
```

```{r}
premium_gamma_model <- svyglm(HICOSTR1_A ~ AGEP_A + SEX_A + RACEALLP_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + 
                                        POVRATTC_A + RATCAT_A + EDUCP_A + ACCSSINT_A +  
                                        DIBEV_A +  PREDIB_A + HYPEV_A +  ASEV_A +  EVERCOVD_A + ANXFREQ_A + DEPFREQ_A +
                                        SMOKELSEV1_A + SMKCIGST_A + DRKLIFE_A + DRKSTAT_A + MODFREQW_A +
                                        REGION + URBRRL23,
                          design = svy_design, 
                          family = Gamma(link = "log"))

summary(premium_gamma_model)
```

```{r}
gamma_diag <- data.frame(
  Fitted = fitted(premium_gamma_model),
  Residuals = residuals(premium_gamma_model, type = "deviance")
)

ggplot(gamma_diag, aes(x = log(Fitted), y = Residuals)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "loess", color = "red") +
  labs(title = "Gamma Model: Deviance Residuals vs Fitted",
       subtitle = "Ideally, the red line is flat and residuals are centered around 0",
       x = "Log(Fitted Values)",
       y = "Deviance Residuals")
```

```{r}
proxy_vif_model <- glm(HICOSTR1_A ~ AGEP_A + SEX_A + RACEALLP_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + 
                                        POVRATTC_A + RATCAT_A + EDUCP_A + ACCSSINT_A +  
                                        DIBEV_A +  PREDIB_A + HYPEV_A +  ASEV_A +  EVERCOVD_A + ANXFREQ_A + DEPFREQ_A +
                                        SMOKELSEV1_A + SMKCIGST_A + DRKLIFE_A + DRKSTAT_A + MODFREQW_A +
                                        REGION + URBRRL23,
    data = premium_data, 
    weights = WTFA_A, 
    family = Gamma(link = "log"))

alias(proxy_vif_model)
```

```{r}
proxy_vif_model <- glm(HICOSTR1_A ~ AGEP_A + SEX_A + RACEALLP_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + 
                                        POVRATTC_A + RATCAT_A + EDUCP_A + ACCSSINT_A +  
                                        DIBEV_A +  PREDIB_A + HYPEV_A +  ASEV_A +  EVERCOVD_A + ANXFREQ_A + DEPFREQ_A +
                                        SMOKELSEV1_A + SMKCIGST_A + DRKSTAT_A + MODFREQW_A +
                                        REGION + URBRRL23,
    data = premium_data, 
    weights = WTFA_A, 
    family = Gamma(link = "log"))

alias(proxy_vif_model)
vif(proxy_vif_model)
```

```{r}
proxy_vif_model <- glm(HICOSTR1_A ~ AGEP_A + SEX_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + 
                                        POVRATTC_A + RATCAT_A + EDUCP_A + ACCSSINT_A +  
                                        DIBEV_A +  PREDIB_A + HYPEV_A +  ASEV_A +  EVERCOVD_A + ANXFREQ_A + DEPFREQ_A +
                                        SMOKELSEV1_A + SMKCIGST_A + DRKSTAT_A + MODFREQW_A +
                                        REGION + URBRRL23,
    data = premium_data, 
    weights = WTFA_A, 
    family = Gamma(link = "log"))

alias(proxy_vif_model)
vif(proxy_vif_model)
```
```{r}
final_gamma_model <- svyglm(HICOSTR1_A ~ AGEP_A + SEX_A + HISPALLP_A + MARITAL_A + NATUSBORN_A + ORIENT_A + 
                                        POVRATTC_A + RATCAT_A + EDUCP_A + ACCSSINT_A +  
                                        DIBEV_A +  PREDIB_A + HYPEV_A +  ASEV_A +  EVERCOVD_A + ANXFREQ_A + DEPFREQ_A +
                                        SMOKELSEV1_A + SMKCIGST_A + DRKSTAT_A + MODFREQW_A +
                                        REGION + URBRRL23,
                          design = svy_design, 
                          family = Gamma(link = "log"))
summary(final_gamma_model)
```

```{r}
nobs(final_gamma_model)
```


```{r}
cooks_d <- cooks.distance(final_gamma_model)

n_obs <- nobs(final_gamma_model)
cutoff <- 4 / n_obs

plot(cooks_d, pch = 20, main = "Cook's Distance Plot", ylab = "Cook's Distance")
abline(h = cutoff, col = "red", lty = 2)

influential_indices <- which(cooks_d > cutoff) 


top_influential_data <- premium_data[names(sort(cooks_d[influential_indices], decreasing = TRUE)[1:10]), ] %>%
   dplyr::select(HICOSTR1_A, AGEP_A, POVRATTC_A, WTFA_A)

print(paste("Number of points above threshold:", length(influential_indices)))
print("Top 10 Most Influential Points:")
print(top_influential_data)
```


```{r}
ggplot(data.frame(Fitted = fitted(final_gamma_model), 
                  Resid = residuals(final_gamma_model, type = "deviance")),
       aes(x = log(Fitted), y = Resid)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "loess", color = "red", se = FALSE) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(title = "Residuals vs. Fitted Values",
       subtitle = "Red line should be flat. Funnel shape means Gamma assumption failed.",
       x = "Log Predicted Premium",
       y = "Deviance Residuals")
```

```{r}
library(survey)

forward_select_svy_wald <- function(full_model, design_obj, alpha = 0.05) {
  
  covariates <- attr(terms(full_model), "term.labels")
  model_family <- full_model$family
  
  selected_covariates <- c()
  remaining_covariates <- covariates
  
  current_form_str <- "HICOSTR1_A ~ 1" 
  
  print("Starting Forward Selection (Wald Tests)...")

  repeat {
    best_p <- Inf
    best_cov <- NULL
    
    for (candidate in remaining_covariates) {
      
      new_form_str <- paste(current_form_str, "+", candidate)
      
      tryCatch({
        check_model <- svyglm(as.formula(new_form_str), 
                              design = design_obj, 
                              family = model_family)
        
        wald_test <- regTermTest(check_model, candidate, method = "Wald")
        p_val <- wald_test$p[1]
        
        if (p_val < best_p) {
          best_p <- p_val
          best_cov <- candidate
        }
        
      }, error = function(e) {
      })
    }
    
    if (is.null(best_cov) || best_p > alpha) {
      print("------------------------------------------------")
      print("Selection Complete. No further variables significant.")
      break
    }
    
    print(paste("Adding:", best_cov, "| Wald P-value:", format.pval(best_p, digits=4)))
    
    current_form_str <- paste(current_form_str, "+", best_cov)
    selected_covariates <- c(selected_covariates, best_cov)
    remaining_covariates <- setdiff(remaining_covariates, best_cov)
  }
  
  final_model <- svyglm(as.formula(current_form_str), design = design_obj, family = model_family)
  return(final_model)
}


final_forward_model <- forward_select_svy_wald(final_gamma_model, svy_design)

summary(final_forward_model)
```

```{r}
ggplot(data.frame(Fitted = fitted(final_forward_model), 
                  Resid = residuals(final_forward_model, type = "deviance")),
       aes(x = log(Fitted), y = Resid)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "loess", color = "red", se = FALSE) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(title = "Residuals vs. Fitted Values",
       subtitle = "Red line should be flat. Funnel shape means Gamma assumption failed.",
       x = "Log Predicted Premium",
       y = "Deviance Residuals")
```


```{r}
backward_select_svy <- function(full_model, design_obj, alpha = 0.05) {
  
  current_model <- full_model
  print(paste("Starting Backward Selection (Wald Tests) with", length(attr(terms(current_model), "term.labels")), "variables..."))
  
  while(TRUE) {
    current_terms <- attr(terms(current_model), "term.labels")
    
    if(length(current_terms) == 0) {
      print("No predictors left.")
      break
    }
    
    p_values <- sapply(current_terms, function(term) {
      tryCatch({
        test <- regTermTest(current_model, term, method = "Wald")
        return(test$p[1])
      }, error = function(e) {
        return(0)
      })
    })
    
    max_p <- max(p_values)
    worst_var <- names(p_values)[which.max(p_values)]
    
    if(max_p > alpha) {
      print(paste("Dropping term:", worst_var, 
                  "| Wald p-value:", round(max_p, 4)))
      
      new_formula <- update(formula(current_model), paste("~ . -", worst_var))
      
      current_model <- svyglm(new_formula, design = design_obj, family = Gamma(link = "log"))
      
    } else {
      print("----------------------------------------------------")
      print("Selection Complete: All remaining variables are significant.")
      break
    }
  }
  
  return(current_model)
}

final_backward_model <- backward_select_svy(final_gamma_model, svy_design)
summary(final_backward_model)
```

```{r}
ggplot(data.frame(Fitted = fitted(final_back_model), 
                  Resid = residuals(final_back_model, type = "deviance")),
       aes(x = log(Fitted), y = Resid)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "loess", color = "red", se = FALSE) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(title = "Residuals vs. Fitted Values",
       subtitle = "Red line should be flat. Funnel shape means Gamma assumption failed.",
       x = "Log Predicted Premium",
       y = "Deviance Residuals")
```

```{r}
hybrid_select_svy <- function(empty_model, full_scope_model, design_obj, 
                                     alpha_enter = 0.05, alpha_remove = 0.05) {
  
  model_family <- empty_model$family
  scope_vars <- attr(terms(full_scope_model), "term.labels")
  
  current_model <- empty_model
  current_form_str <- paste(deparse(formula(current_model), width.cutoff = 500), collapse = " ")
  
  print(paste("Starting Hybrid Selection (Enter <", alpha_enter, "| Remove >", alpha_remove, ")..."))
  
  iter <- 0
  max_iter <- 50 
  
  repeat {
    iter <- iter + 1
    if(iter > max_iter) { 
      print("WARNING: Max iterations reached. Stopping to prevent infinite loop.")
      break 
    }
    
    print(paste("--- Iteration", iter, "---"))
    
    current_vars <- attr(terms(current_model), "term.labels")
    possible_adds <- setdiff(scope_vars, current_vars)
    
    action_taken <- FALSE
    
    best_p_add <- Inf
    best_var_add <- NULL
    
    if(length(possible_adds) > 0) {
      for(cand in possible_adds) {
        new_form_str <- paste(current_form_str, "+", cand)
        
        tryCatch({
          temp_mod <- svyglm(as.formula(new_form_str), design = design_obj, family = model_family)
          wt <- regTermTest(temp_mod, cand, method = "Wald")
          p_val <- wt$p[1]
          
          if(p_val < best_p_add) {
            best_p_add <- p_val
            best_var_add <- cand
          }
        }, error = function(e) {})
      }
    }
    
    if(!is.null(best_var_add) && best_p_add < alpha_enter) {
      print(paste("++ ADDING:", best_var_add, "| P-value:", format.pval(best_p_add, digits=4)))
      
      current_form_str <- paste(current_form_str, "+", best_var_add)
      current_model <- svyglm(as.formula(current_form_str), design = design_obj, family = model_family)
      action_taken <- TRUE
    }
    
    current_vars_check <- attr(terms(current_model), "term.labels")
    
    if(length(current_vars_check) > 0) {
      worst_p_drop <- -1
      worst_var_drop <- NULL
      
      for(existing in current_vars_check) {
        if(!is.null(best_var_add) && existing == best_var_add) next
        
        tryCatch({
          wt <- regTermTest(current_model, existing, method = "Wald")
          p_val <- wt$p[1]
          
          if(p_val > worst_p_drop) {
            worst_p_drop <- p_val
            worst_var_drop <- existing
          }
        }, error = function(e) {})
      }
      
      if(!is.null(worst_var_drop) && worst_p_drop > alpha_remove) {
        print(paste("-- DROPPING:", worst_var_drop, "| P-value:", format.pval(worst_p_drop, digits=4)))
        
        current_form_str <- paste(deparse(update(formula(current_model), paste("~ . -", worst_var_drop)), width.cutoff = 500), collapse = " ")
        current_model <- svyglm(as.formula(current_form_str), design = design_obj, family = model_family)
        action_taken <- TRUE
      }
    }
    
    if(!action_taken) {
      print("------------------------------------------------")
      print("Selection Complete. Model is stable.")
      break
    }
  }
  
  return(current_model)
}

null_model <- svyglm(HICOSTR1_A ~ 1, 
                      design = design_final, 
                      family = Gamma(link = "log"))

full_model <- final_gamma_model 

final_hybrid_model <- hybrid_select_svy(null_model, full_model, svy_design, alpha_remove = 0.1)

summary(final_hybrid_model)
```

```{r}
ggplot(data.frame(Fitted = fitted(final_back_model), 
                  Resid = residuals(final_back_model, type = "deviance")),
       aes(x = log(Fitted), y = Resid)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "loess", color = "red", se = FALSE) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(title = "Residuals vs. Fitted Values",
       subtitle = "Red line should be flat. Funnel shape means Gamma assumption failed.",
       x = "Log Predicted Premium",
       y = "Deviance Residuals")
```

```{r}
get_model_metrics <- function(model, name) {
  r2 <- 1 - (model$deviance / null_model$deviance)
  
  num_vars <- length(attr(terms(model), "term.labels"))

  return(data.frame(
    Model = name,
    Num_Variables = num_vars,
    Pseudo_R2 = round(r2, 4),
    Deviance = round(model$deviance, 2)
  ))
}

comparison_table <- rbind(
  get_model_metrics(final_backward_model, "Backward (Wald)"),
  get_model_metrics(final_forward_model, "Forward (Wald)"),
  get_model_metrics(final_hybrid_model, "Hybrid (Wald)")
)

comparison_table
```

```{r}
summary(final_backward_model)
```

